general:
steps:
  gctsDeploy:
    host: "https://tst.opensap.consarea.com:44300"
    client: "100"
    abapCredentialsId: "SGRNJ7OB_CRED"
    repository: "SGRNJ7OB-workbench"
    remoteRepositoryURL: "https://github.com/SGRNJ7OB/workbench"
    role: "SOURCE"
    vSID: "SGR"
    verbose: true
    type: "GITHUB"
    rollback: false
